# Generated by Django 5.0.1 on 2024-03-23 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytriTravel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createaccount',
            name='city',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='date_of_travel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='package_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
